# -*- coding: utf-8 -*-
"""Copy of Data-Puzzles / Spider Walk

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/113ojRb_momO_hU7vpO7H-sc1Ovp881aj

# Intro

**Every minute**, the spider moves at an angle taken at random **uniformly between 0 and 360degrees**, at a distance taken at random **uniformly between 0 and 2m**.

The spider starts at coordinates (0, 0) and my place can be represented by the area determined by the square delimited by upper-left corner (10, 10) and lower-right corner (15, 6) (unit is meter)

What's the probability the spider is at my place after 240mn?

# Solve
"""

import numpy as np
from tqdm import trange
from math import pi

N_MINUTES = 240

UPPER_LEFT_CORNER = (10, 10)
LOWER_RIGHT_CORNER = (15, 6)

def trial():
    th = np.random.uniform(0, 2*pi, size=N_MINUTES)
    r  = np.random.randint(0, 3, size=N_MINUTES)
    x = np.sum(r * np.cos(th))
    y = np.sum(r * np.sin(th))

    x1, y1 = UPPER_LEFT_CORNER
    x2, y2 = LOWER_RIGHT_CORNER
    return (x1 <= x <= x2) and (y2 <= y <= y1)

proba = np.mean([trial() for _ in trange(100_000)])
proba

round((proba * 100) * 10) / 10

